---
title: "How I Imagine Getting Old"
description: "Originally posted on Facebook, 25 April 2016."
date: 2016-04-25
categories: [Poems]
draft: false
---

| \~\~\~\~\~\~\~\~\~\~\~\~\~\~\~\~\~\~\~\~\~\~\~\~\~
| Today, after a long long time,
| I'm lying down on the grass,
| Looking up at the stars.
| And in this moment of peace,
| in this serenity,
| I feel myself.
| I don't feel anxious,
| What is,
| What could be,
| I feel I accept.
| This is how I imagine, being old
| When wisdom is my companion,
| When all the things,
| Which used to frustrate me,
| Bring a smile to my face
| When I can take, all the time in the world
| To just sit and bathe in the sun,
| To take the next step,
| And feel the grass beneath my feet,
| This is how I imagine, being old.
| To be able to spend my time with you,
| without being in a hurry,
| To just hold you,
| And walk.
| To just look at you,
| And talk.
| With all the time in the world,
| And nowhere else I would go.
| I look forward to have grey hair,
| And finally white.
| This is how I imagine getting old.
| I would not be in a hurry to breathe fast,
| Not be anxious, to think fast.
| I would take my time,
| This is how I imagine, getting old.
| Being old does not mean,
| I can't live life fully,
| For me it means, the real time to live life,
| To enjoy everything, with the knowledge of the past,
| And of the future.
| At this moment of my life,
| My future is full of possibilities,
| My present is full of choices,
| My past is not so long
| I don't have so many experiences
| But when I'm old,
| My past would be the longest,
| I would know everything about this past,
| I would not have so many choices in the present,
| And I would know my future.
| I would recall the people who came,
| The people who stayed,
| and those who left,
| When there is no more anger in my heart,
| but acceptance and forgiveness.
| The sweet moments of life,
| When one knows,
| All is said and done.
| And is free,
| To witness the cycle moving,
| on and on,
| I look forward to being old.
| To take my time.
| The best phase of life for me
| This is how I imagine, getting old.
| \~\~\~\~\~\~\~\~


*25 April 2016.* [Originally posted on Facebook](https://www.facebook.com/abhi18av/posts/pfbid02c3V5hh2m2QsaRHz2RNPAqSHpgj6ynjxKn5VW4kEcHLYgSKs7Ak2veXjZ16Q43ycEl).
