---
title: "Are you an Angel?"
date: 2017-06-27
categories: [Poems]
draft: false
---

It's wonderful the way hazy memory of words, myths and stories gives us ways to express ourselves.

They say, life is lived in Circles. I feel, there's some truth to it but perhaps it's an infinite spiral - the very same feelings, reactions, thoughts - only slightly different.

Each ring becoming bigger with maturity, moving away from nothing towards the distant nothing.

@\~@\~@\~@

| Are you an Angel?
|
| Of course I'm an angel!
| Not a proud fallen angel,
| but a little, melancholic one.
|
| My deed, is to observe,
| My writ is to watch,
| And whisper in the ears of God.
|
| Raziel is how I was named,
| keeper of secrets,
| seeker of knowledge.
|
| I saw you and I spread my wings
| without a thought,
| without hesitation,
| I see the most wonderful secret.
|
| I spread my wings,
| a black,
| a brown,
| a yellow,
| and white,
| all together
| and so I flew down.
|
| And here, I stand - before you.

@\~@\~@\~@

*27 June 2017.* [Originally posted on Facebook](https://www.facebook.com/abhi18av/posts/pfbid0kUdxkfPUdA4aSWcq2PEmixoay3PMaTcKDrYeUw3XHfcJ1xnvTxvLeMDYYnhHvcD8l).
