---
title: "The thrice-born Self"
date: 2026-08-04
categories: [Poems]
draft: false
---

*Dedication of my PhD thesis, Stellenbosch University, 2026.*

And so, comes to an end, the easiest and hardest of my educational endeavours. What follows is the story of this season of my life. The life that happened to Me - *in verse*; while I was busy doing what life entails - *in prose*.

---

| This, my beloved,
|     ~~is because of Us~~,
|     is despite You and I.
| I bow in reverence to You.
|
| This flesh and bone,
|     formed in the *womb* of my mother,
|         with the [essence]{.underline} of my parents' dreams.
| I was given a Name.
|
| I glimpsed that Self in my youth,
|     formed in the *womb* of this world,
|         with the [echoes]{.underline} of my parents' dreams.
| The conception of Myself.
|
| Then I met You, my beloved midwife,
|     like a storm in spring.
| Who taught Me,
|     the eternal dance of endings and renewals.
| Who pierced my heart with an arrow,
|     and liberated a thousand dreams.
| Who stayed with Me,
|     through the arduous labor pain,
|         and helped Me give birth to Myself.
|
| When the spring storm passed,
|     the rose garden of my heart,
|         witnessed its many flowers wither and fall.
| The burial of every rose,
|     became a *womb* for a new spring.
|
| I found Myself,
|     and earned this Name.
| The ever-renewing, ever-changing,
|     and ever-becoming Self - अभिनव ( Abhinav )
