---
title: "For the one who has two beating hearts"
date: 2016-05-05
categories: [Poems]
draft: false
---

I saw the pic of the last class and I guess, the last five minutes were an experience. So, I scribbled something for the one teacher who has been the most memorable one for me - Anamika Ma'am

So, here goes...

\~\~\~\~\~\~\~\~\~\~

| For the one who has two beating hearts,
| may the little ones beat stronger everyday,
| and the bigger one become greater still.
|
| For showing faith in me,
| when all the red ink spoke otherwise.
|
| For guiding me through trust, not commands
| through subtle suggestions, not verdicts
|
| For making me realize that,
| there are those precious few,
| who'd understand my unformed thoughts,
| and be a joy through thick and thin.
|
| You know, I haven't attended classes much,
| but God knows, I have learned your lessons.
| Lessons in words and in deeds.
|
| For the one who has twice as many hearts.
| The ambitious fool that I am,
| there are still naive good parts.
|
| Thank you for letting me be myself.

\~\~\~\~\~\~\~\~\~\~\~\~\~\~\~\~\~\~\~\~\~\~\~\~\~\~\~\~\~\~

P.S. Ma'am if you read this, bs ab pass kr dena - MC tedha subject hai;p

P.P.P Yes, everyone. Post-supplementary exam, 9 o'clock musings into the night are very elegant indeed.

\.

\.

\.

I recommend you try it;D

*5 May 2016.* [Originally posted on Facebook](https://www.facebook.com/abhi18av/posts/pfbid02Los9zfq9kN6vUAPPoUdTnr9UnoufikRPUWmqRhZc8EUtUk5pQhUaQBCoTiVRCse4l).
